### ISSUE TITLE
Integrate review requests

### ISSUE THREAD

**Issue by nikku** [nikku/wuffle#22]
Right now, the reviewer icons are gone the moment a collaborator submits a review.

The reason for that is that we look into `requested_reviewers` only and a user that provided the review is not in that collection anymore.

__Tasks__

* [ ] Hook into [`pull_request_review`](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent) events and store _reviews_ with their reviewer and state within the pull_request
* [ ] Sync reviews via background sync
* [ ] Display reviewers that gave reviews
* [ ] Indicate review state via updated indicator icon
* [ ] Link review via reviewer avatar

__Current Card__

![image](https://user-images.githubusercontent.com/58601/59142530-001ae700-89c0-11e9-8671-ebbe7d3f02eb.png)
