### ISSUE TITLE
Integrate PR checks and statuses

### ISSUE THREAD

**Issue by nikku** [nikku/wuffle#41]
Visualize the checks and statuses, effectively quality gates on pull-requests.

We should attempt to normalize both, checks and statuses in the back-end, otherwise the implemementation on the board will probably be painful.

## Resources

* [Statuses](https://developer.github.com/v3/repos/statuses/) - the legacy way of attaching information to a PR
* [Checks](https://developer.github.com/v3/checks/) - the modern way / an advanced variant of statuses

#### Back-end

* [ ] background synche from GitHub
* [ ] update on GitHub events
* [ ] expose to everyone with _view access_ on a PR
* [ ] Generate update whenever they change

#### Board

* [ ] show visually on a expanded PR card as well as on a linked / attached PR
* [ ] clickable (goes to place that backs up the check / status)
