### ISSUE TITLE
Add ability to whitelist organizations to appear on the board

### ISSUE THREAD

**Issue by nikku** [nikku/wuffle#75]
__Is your feature request related to a problem? Please describe.__

Public GitHub apps that feed the board can be installed without restrictions via GitHub.

__Describe the solution you'd like__

* [ ] Add ability to filter GitHub organizations via config for which
    * [ ] Issues will be Background Synched
    * [ ] Webhooks will be reacted upon
